name: name
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    external: true