name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files for debugging
        run: ls -R

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Create GraphQL client directory
        run: mkdir -p ./ModuloEquipaje/src/main/resources/graphql-client

      - name: Install dependencies
        run: mvn install -DskipTests
        working-directory: ./ModuloEquipaje

      - name: Run tests
        run: mvn test
        working-directory: ./ModuloEquipaje

      - name: Run Sonar analysis
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Felipey55-ModuloEquipaje -Dsonar.jacoco.reportPaths=target/jacoco.exec || true
        working-directory: ./ModuloEquipaje
